### ISSUE TITLE
Release without last version number digit

### ISSUE THREAD

**Issue by ravage84** [kapsiR/HaveIBeenPwnedKeePassPlugin#18]
Hi,

Today, I was informed about the newest release available `0.8.0.4` (already installed):

![grafik](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/assets/625761/522876ba-a87b-4862-835c-2b711d156aec)

But when I checked the last available release here on the GitHub repo, I just found version [`v0.8.0`](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/releases/tag/v0.8.0).

Also, there was no such [tag ](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/tags).

I found a commit, though, in which the version number was changed to [`0.8.0.4`](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/commit/4bb8a108b2ab3daa944d0fd57c4044c59a5f46c1).

The only [differences between `v0.8.0` and `0.8.0.4`](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/compare/v0.8.0...main) seem to be 

> 1. This makes the v8.0 release public (update check shows new version available)
>  2. Fix changelog reference link 

I was confused as why the "official" release wasn't the one I was informed about.

It would be great, if there was always a corresponding release including [a change log entry](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/blob/4bb8a108b2ab3daa944d0fd57c4044c59a5f46c1/CHANGELOG.md#080---2024-04-21).

Thus, in this case I would have either expected to find just a release `0.8.0.4`, including the `x.y.z.4`, or one in addition to a `0.8.0` release.

**Comment by kapsiR** [comment]
Thanks for the report and thanks for using the plugin!  
I hope I can clarify the process with my answer.

The released version is this commit: https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/commit/18d3809be2c04e2d911860371b37976b39c2e7c4  
The revision changes with every commit due to my versioning system (["git height"](https://github.com/dotnet/Nerdbank.GitVersioning?tab=readme-ov-file#what-is-git-height))

This time I choosed a "progressive rollout", where users with release notifications on GitHub would be the first that could try it out.  
That's the reason why the `KeePass.version` file got an update a few days after the release.

KeePass is using the `FileVersion` for updates, so I can't change that, but:
 - [You can verify every release by the `ProductVersion`](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/security/policy#releases):  
    `(Get-Item .\HaveIBeenPwnedPlugin.dll).VersionInfo.ProductVersion` --> `0.8.0+18d3809be2`

This specific behavior is widely used, e.g.:
 - `(Get-Item 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Core.dll').VersionInfo.FileVersion` --> `8.0.424.16909`  
 - `(Get-Item 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Core.dll').VersionInfo.ProductVersion` --> `8.0.4+2d7eea252964e69be94cb9c847b371b23e4dd470`

Due to this reasons, I won't change the entire workflow here and I hope you can understand that.
